export {};

/**
 * M4 - Orchestrator
 *
 * 核心概念：
 * - Orchestrator 只负责：分解任务、调度 subagent、合并结果
 * - Orchestrator 不写代码，不执行具体工作
 * - 与 subagent 的通信通过结构化的 TaskSpec / TaskResult
 */

// ---- 通信协议 ----

interface TaskSpec {
  id: string;
  type: "implement" | "test" | "review";
  description: string;
  inputs: Record<string, string>; // 输入数据（文件内容、接口定义等）
  outputFiles: string[];          // 期望产出的文件列表
  constraints: string[];          // 约束条件
}

interface TaskResult {
  taskId: string;
  status: "success" | "failed";
  outputs: Record<string, string>; // 文件名 → 内容
  summary: string;
  tokensUsed: number;
}

// ---- Mock Subagent（模拟实际执行）----

async function mockSubagent(spec: TaskSpec): Promise<TaskResult> {
  await sleep(100 + Math.random() * 200);

  if (spec.type === "implement") {
    return {
      taskId: spec.id,
      status: "success",
      outputs: {
        [spec.outputFiles[0]]: `// Generated by subagent for: ${spec.description}\nexport function placeholder() {}\n`,
      },
      summary: `Implemented ${spec.description}`,
      tokensUsed: 1200,
    };
  }

  if (spec.type === "test") {
    return {
      taskId: spec.id,
      status: "success",
      outputs: {
        [spec.outputFiles[0]]: `// Tests for: ${spec.description}\ndescribe('${spec.id}', () => { it('works', () => {}) })\n`,
      },
      summary: `Tests written for ${spec.description}`,
      tokensUsed: 800,
    };
  }

  return { taskId: spec.id, status: "failed", outputs: {}, summary: "Unknown task type", tokensUsed: 0 };
}

// ---- Orchestrator ----

class Orchestrator {
  private results: TaskResult[] = [];

  // Step 1: 把 PRD 分解为任务列表（实际场景由 LLM 生成）
  decompose(prd: string): TaskSpec[] {
    console.log(`\n[Orchestrator] Decomposing PRD: "${prd.slice(0, 60)}..."`);

    // Mock 分解结果
    return [
      {
        id: "impl-auth",
        type: "implement",
        description: "JWT authentication middleware",
        inputs: { "interface.ts": "export interface User { id: string; email: string }" },
        outputFiles: ["src/auth/middleware.ts"],
        constraints: ["Must use jsonwebtoken library", "Token expiry: 24h"],
      },
      {
        id: "impl-user",
        type: "implement",
        description: "User CRUD endpoints",
        inputs: { "interface.ts": "export interface User { id: string; email: string }" },
        outputFiles: ["src/routes/users.ts"],
        constraints: ["RESTful design", "Validate all inputs"],
      },
      {
        id: "test-auth",
        type: "test",
        description: "Tests for JWT middleware",
        inputs: {},
        outputFiles: ["tests/auth.test.ts"],
        constraints: ["Cover success and failure cases"],
      },
    ];
  }

  // Step 2: 并行调度所有独立任务
  async dispatch(tasks: TaskSpec[]): Promise<void> {
    console.log(`\n[Orchestrator] Dispatching ${tasks.length} tasks in parallel`);

    const promises = tasks.map(async (spec) => {
      console.log(`  → Subagent started: ${spec.id} (${spec.type})`);
      const result = await mockSubagent(spec);
      this.results.push(result);
      const icon = result.status === "success" ? "✅" : "❌";
      console.log(`  ${icon} Subagent done: ${spec.id} — ${result.summary}`);
      return result;
    });

    await Promise.allSettled(promises);
  }

  // Step 3: 合并所有 subagent 的输出
  merge(): Record<string, string> {
    console.log(`\n[Orchestrator] Merging results from ${this.results.length} subagents`);

    const merged: Record<string, string> = {};
    const conflicts: string[] = [];

    for (const result of this.results) {
      if (result.status !== "success") continue;

      for (const [file, content] of Object.entries(result.outputs)) {
        if (file in merged) {
          conflicts.push(file);
          merged[file] = `// CONFLICT: merged from multiple subagents\n${merged[file]}\n// --- AND ---\n${content}`;
        } else {
          merged[file] = content;
        }
      }
    }

    if (conflicts.length > 0) {
      console.log(`  ⚠️  Conflicts detected in: ${conflicts.join(", ")}`);
    }

    const totalTokens = this.results.reduce((s, r) => s + r.tokensUsed, 0);
    console.log(`  Files merged: ${Object.keys(merged).length}`);
    console.log(`  Total tokens used: ${totalTokens.toLocaleString()}`);

    return merged;
  }

  // 完整流程
  async run(prd: string): Promise<Record<string, string>> {
    const tasks = this.decompose(prd);
    await this.dispatch(tasks);
    return this.merge();
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

// ---- 演示 ----

async function main() {
  console.log("=== Orchestrator Demo ===");

  const prd = `Build a REST API with JWT authentication and user management.
Users can register, login, and manage their profile.
All endpoints must be authenticated except register and login.`;

  const orchestrator = new Orchestrator();
  const outputs = await orchestrator.run(prd);

  console.log("\n--- Final outputs ---");
  for (const [file, content] of Object.entries(outputs)) {
    console.log(`\n📄 ${file}:\n${content.slice(0, 120)}...`);
  }

  console.log("\n--- 关键观察 ---");
  console.log("1. Orchestrator 只做三件事：分解、调度、合并——不写代码");
  console.log("2. 所有 subagent 并行执行，总时间取决于最慢的那个");
  console.log("3. 冲突检测：两个 subagent 修改同一文件时需要合并策略");
}

main().catch(console.error);
